import type { Metadata } from 'next';
import '@/styles/globals.css';
import { fontSans } from '@/config/font';
import clsx from 'clsx';
import { PropsWithChildren } from 'react';
import Navbar from '@/components/shared/layout/navbar/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={clsx(
          'min-h-screen text-foreground bg-background font-sans antialiased',
          fontSans.variable,
        )}
      >
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
